name: fetch-yfinance
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
      SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
      SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
      SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
      SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: Commit updated DB
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add data/market.sqlite3 || true
          git commit -m "Update DB $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo 'No changes'
          git push
      - name: List data dir (debug)
        run: ls -al data || true